# A vis mac file that creates multiple vis scenes
#
/vis/open OGL
#
# Create 2 scenes
#
/vis/scene/create trajectoryScene
/vis/scene/create hitsScene
#
# Add geometry to both scenes
#
/vis/drawVolume
#
# Attach scene to sceneHandler
#
/vis/sceneHandler/attach hitsScene
#
# Set parameters
#
/vis/viewer/set/viewport
#
# Execute the visualization
#
/vis/viewer/refresh
#
# declare end of visualization
#
/vis/viewer/flush