# start up
/run/initialize
#
# open a file to store our histogram
/analysis/openFile pdd
#
# activate the pdd graph
/analysis/h1/setActivation 0
#
# activate dose profile graph as well
/analysis/h1/setActivation 1
#
# run a simulation
/run/beamOn 10000000
#
# save to the file
/analysis/write
/analysis/closeFile
#
# reset the graphs
/analysis/h1/setActivation 0 false
/analysis/h1/setActivation 1 false
